// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py for languages Go
// from https://unpkg.com/lucide-static@latest/font/lucide.css
// for use with https://unpkg.com/lucide-static@latest/font/lucide.ttf

package fonts

import (
	IconFontCppHeaders "bitbox-editor/resources/fonticons"

	"golang.org/x/exp/slices"
)

type Font struct {
	Filenames       [][2]string
	Min, Max16, Max int
	Icons           map[string]string
}

var (
	icons      = IconFontCppHeaders.IconsLucide
	IconsInUse = make([]string, 0)
)

func Icon(name string) string {
	out := icons.Icons[name]
	if !slices.Contains(IconsInUse, out) {
		IconsInUse = append(IconsInUse, out)
	}
	return out
}
