package flags

import "github.com/AllenDang/cimgui-go/imgui"

type TableFlags imgui.TableFlags

const (
	TableFlagsNone                       = TableFlags(imgui.TableFlagsNone)
	TableFlagsResizable                  = TableFlags(imgui.TableFlagsResizable)
	TableFlagsReorderable                = TableFlags(imgui.TableFlagsReorderable)
	TableFlagsHideable                   = TableFlags(imgui.TableFlagsHideable)
	TableFlagsSortable                   = TableFlags(imgui.TableFlagsSortable)
	TableFlagsNoSavedSettings            = TableFlags(imgui.TableFlagsNoSavedSettings)
	TableFlagsContextMenuInBody          = TableFlags(imgui.TableFlagsContextMenuInBody)
	TableFlagsRowBg                      = TableFlags(imgui.TableFlagsRowBg)
	TableFlagsBordersInnerH              = TableFlags(imgui.TableFlagsBordersInnerH)
	TableFlagsBordersOuterH              = TableFlags(imgui.TableFlagsBordersOuterH)
	TableFlagsBordersInnerV              = TableFlags(imgui.TableFlagsBordersInnerV)
	TableFlagsBordersOuterV              = TableFlags(imgui.TableFlagsBordersOuterV)
	TableFlagsBordersH                   = TableFlags(imgui.TableFlagsBordersH)
	TableFlagsBordersV                   = TableFlags(imgui.TableFlagsBordersV)
	TableFlagsBordersInner               = TableFlags(imgui.TableFlagsBordersInner)
	TableFlagsBordersOuter               = TableFlags(imgui.TableFlagsBordersOuter)
	TableFlagsBorders                    = TableFlags(imgui.TableFlagsBorders)
	TableFlagsNoBordersInBody            = TableFlags(imgui.TableFlagsNoBordersInBody)
	TableFlagsNoBordersInBodyUntilResize = TableFlags(imgui.TableFlagsNoBordersInBodyUntilResize)
	TableFlagsSizingFixedFit             = TableFlags(imgui.TableFlagsSizingFixedFit)
	TableFlagsSizingFixedSame            = TableFlags(imgui.TableFlagsSizingFixedSame)
	TableFlagsSizingStretchProp          = TableFlags(imgui.TableFlagsSizingStretchProp)
	TableFlagsSizingStretchSame          = TableFlags(imgui.TableFlagsSizingStretchSame)
	TableFlagsNoHostExtendX              = TableFlags(imgui.TableFlagsNoHostExtendX)
	TableFlagsNoHostExtendY              = TableFlags(imgui.TableFlagsNoHostExtendY)
	TableFlagsNoKeepColumnsVisible       = TableFlags(imgui.TableFlagsNoKeepColumnsVisible)
	TableFlagsPreciseWidths              = TableFlags(imgui.TableFlagsPreciseWidths)
	TableFlagsNoClip                     = TableFlags(imgui.TableFlagsNoClip)
	TableFlagsPadOuterX                  = TableFlags(imgui.TableFlagsPadOuterX)
	TableFlagsNoPadOuterX                = TableFlags(imgui.TableFlagsNoPadOuterX)
	TableFlagsNoPadInnerX                = TableFlags(imgui.TableFlagsNoPadInnerX)
	TableFlagsScrollX                    = TableFlags(imgui.TableFlagsScrollX)
	TableFlagsScrollY                    = TableFlags(imgui.TableFlagsScrollY)
	TableFlagsSortMulti                  = TableFlags(imgui.TableFlagsSortMulti)
	TableFlagsSortTristate               = TableFlags(imgui.TableFlagsSortTristate)
	TableFlagsSizingMask                 = TableFlags(imgui.TableFlagsSizingMask)
)
